name: Node.js CI

on:
  push:
    branches:
      - master
    tags:
      - download.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn start
        env:
          FSLG_FILE_URI: ${{ secrets.FSLG_FILE_URI }}
          FSLG_DOWNLOAD_PASSWORD: ${{ secrets.FSLG_DOWNLOAD_PASSWORD }}
